CREATE TABLE ERC721NFTTransfers(
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    SentTo NVARCHAR(1000) NOT NULL,
    SentFrom NVARCHAR(1000) NOT NULL,
    BlockNumber BIGINT NOT NULL,
    TokenId INT NOT NULL,
    NFTContractAddress NVARCHAR(1000) NOT NULL,
    TxHash NVARCHAR(1000) NOT NULL,
)
